<?php
    $matriz_entreterimento = array
    (
        array(
            "Maze-runner",
            "Maze-runner: Correr ou morrer",
            "Em um futuro, meio apocalíptico, meio utópico, o jovem Thomas é escolhido para enfrentar o sistema. Ao acordar dentro de um escuro elevador em movimento, ele não consegue se lembrar nem de seu nome. Na comunidade isolada em que foi abandonado, ele conhece outros garotos que passaram pelo mesmo. Para conseguir escapar, Thomas precisa descobrir os sombrios segredos guardados em sua mente e correr muito.",
            "https://entreterse.com.br/wp-content/uploads/2018/09/maxresdefault-1-1-e1537141619318.jpg"),
        array(
            "Maze-runner",
            "Maze-runner: Prova de Fogo",
            "Após escapar do labirinto, Thomas e os garotos que o acompanharam em sua fuga encontram com uma realidade bem diferente: a superfície da Terra foi queimada pelo sol e eles precisam lidar com criaturas disformes chamadas Cranks.",
            "https://bipolaridadesoficial.files.wordpress.com/2016/05/prova-de-fogo.png?w=820&h=312&crop=1"),
        array(
            "Maze-runner",
            "Maze runner: A cura Mortal",
            "No terceiro filme da saga, Thomas (Dylan O' Brien) embarca em uma missão para encontrar a cura para uma doença mortal e descobre que os planos da C.R.U.E.L podem trazer consequências catastróficas para a humanidade. Agora, ele tem que decidir se vai se entregar para a C.R.U.E.L e confiar na promessa da organização de que esse será seu último experimento.",
            "https://www.clickguarulhos.com.br/wp-content/uploads/2018/01/20180130-maze-runner-cura-mortal-pre-estreia-01.jpg"),
        array(
            "Capita-marvel",
            "Capitã Marvel",
            "Capitã Marvel, parte do exército de elite dos Kree, uma raça alienígena, encontra-se no meio de uma batalha entre seu povo e os Skrulls. Ao tentar impedir uma invasão de larga escala na Terra, em 1995, ela tem memórias recorrentes de uma outra vida, como Carol Danvers, agente da Força Aérea norte-americana. Com a ajuda de Nick Fury, Capitã Marvel precisa descobrir os segredos de seu passado e pôr um fim ao conflito intergalático com os Skrulls",
            "http://nerdficina.com.br/wp-content/uploads/2018/10/IMG_20181018_101722.jpg"), 
        array(
            "Como_treinar_seu_Dragao",
            "Como Treinar seu Dragão",
            "Na ilha de Berk, os vikings dedicam a vida a combater e matar dragões. Soluço (Jay Baruchel), filho do chefe Stoico (Gerard Butler), não é diferente. Ele sonha em matar um dragão e provar seu valor ao pai, apesar da descrença geral. Um dia, por acaso, ele acerta um dragão que jamais foi visto, chamado Fúria da Noite. Ao procurá-lo, no dia seguinte, Soluço não consegue matá-lo e acaba soltando-o. Só que ele perdeu parte da cauda e, com isso, não consegue mais voar. Soluço passa a trabalhar em um artefato que possa substituir a parte perdida e, aos poucos, se aproxima do dragão. Só que, paralelamente, Stoico autoriza que o filho participe do treino para dragões, cuja prova final é justamente matar um dos animais.",
            "https://www.semprefamilia.com.br/alem-da-tela/wp-content/uploads/sites/7/2015/09/ComoTreinarSeuDrag%C3%A3o-e1442410052234-1180x472.jpg"),
        array(
            "Como_treinar_seu_Dragao",
            "Como treinar seu Dragão 2",
            "Cinco anos se passaram desde que Soluço estabeleceu a paz com os dragões e vive em harmonia, na Ilha de Berk, com Banguela. Eles voam, apostam corridas e se divertem muito. Em uma destas aventuras, descobrem uma caverna secreta cheia de dragões. Agora, a dupla luta para proteger Berk de um guerreiro perigoso, chamado Drago Bludvist, que deseja controlar todos os dragões existentes.",
            "https://culturamaniac.files.wordpress.com/2014/06/como-treinar-seu-dragc3a3o-2-movie.jpg"),
        array(
            "Como_treinar_seu_Dragao",
            "Como treinar seu dragão 3",
            "Soluço busca realizar seu grande sonho de encontrar um lar pacífico onde os dragões possam viver em segurança. Lá, Banguela descobre uma companheira, assim como ele, mas um tanto selvagem. Mas é quando o perigo começa a rondar o lar, que a dupla Banguela e Soluço é testada e precisa tomar decisões difíceis para salvar suas espécies.",
            "https://i2.wp.com/pipocanerd.com/wp-content/uploads/2018/06/como-treinar-seu-dragao-3-sinopse-detalhes-e-cartaz-do-filme-pipoca-nerd.jpg?fit=1280%2C720"),
        array(
            "Rei-leao",
            "Rei Leão",
            "Simba (Donald Glover) é um jovem leão cujo destino é se tornar o rei da selva. Entretanto, uma armadilha elaborada por seu tio Scar (Chiwetel Ejiofor) faz com que Mufasa (James Earl Jones), o atual rei, morra ao tentar salvar o filhote. Consumido pela culpa, Simba deixa o reino rumo a um local distante, onde encontra amigos que o ensinam a mais uma vez ter prazer pela vida",
            "https://studiosol-a.akamaihd.net/uploadfile/letras/playlists/e/7/f/e/e7fe0def1675451997fc60bcb880eab4.jpg"),
        array(
            "Annabelle",
            "Annabelle",
            "John Form acha que encontrou o presente ideal para sua esposa grávida, uma boneca vintage. No entanto, a alegria do casal não dura muito. Uma noite terrível, membros de uma seita satânica invadem a casa do casal em um ataque violento. Ao tentarem invocar um demônio, eles mancham a boneca de sangue, tornando-a receptora de uma entidade do mal.",
            "http://br.web.img2.acsta.net/r_640_360/newsv7/18/11/27/21/28/4719684.jpg"),
        array(
            "Annabelle",
            "Annabelle 2: a criação do mal",
            "Anos após a trágica morte de sua filha, um habilidoso artesão de bonecas e sua esposa decidem, por caridade, acolher em sua casa uma freira e dezenas de meninas desalojadas de um orfanato. Atormentado pelas lembranças traumáticas, o casal ainda precisa lidar com um amendrontador demônio do passado: Annabelle, criação do artesão.",
            "http://ultimatodobacon.com/wp-content/uploads/2017/08/ANABELLE-2.jpg"),
        array(
            "Annabelle",
            "Annabelle 3: De volta pra casa",
            "Os investigadores paranormais Ed e Lorraine Warren mantêm a boneca Annabelle trancada em uma sala de artefatos em sua casa. No entanto, em uma noite terrível, Annabelle desperta outros espíritos malignos e ameaça a jovem filha do casal e suas amigas.",
            "http://www.aconteceempetropolis.com.br/wp-content/uploads/2019/06/annabelle-3.jpg"),
        array(
            "Toy-story",
            "Toy Story",
            "O aniversário de Andy está chegando e os brinquedos estão nervosos. Afinal de contas, eles temem que um novo brinquedo possa substituí-los. Liderados por Woody, um caubói que é também o brinquedo predileto de Andy, eles montam uma escuta que lhes permite saber dos presentes ganhos. Entre eles está Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Isto aos poucos gera ciúmes em Woody, que tenta fazer com que ele caia atrás da cama. Só que o plano dá errado e Buzz cai pela janela. É o início da aventura de Woody, que precisa resgatar Buzz também para limpar sua barra com os outros brinquedos.",
            "https://www.papodecinema.com.br/wp-content/uploads/2013/12/20190621-toy-story-papo-de-cinema.jpg"),
        array(
            "Toy-story",
            "Toy Story 2",
            "Woody tenta salvar um brinquedo que acaba indo parar em um bazar de usados, mas termina por ser sequestrado por um colecionador que pretende vendê-lo a um museu japonês. Na casa do sequestrador, Woody descobre que, no passado, foi protagonista de um famoso seriado de TV e por isso é um brinquedo muito valioso. Ele conhece os demais integrantes de sua coleção e, enquanto isso, os demais brinquedos, liderados por Buzz Lightyear, partem em uma atrapalhada operação de resgate.",
            "https://4.bp.blogspot.com/-ORGZSiGGDtw/W71aZtYFN0I/AAAAAAAABpI/C0-OK4IcOhI7VdfhtRpMaHdNrg-KN5KDwCLcBGAs/s1600/1539132837989.JPEG"),
        array(
            "Toy-story",
            "Toy Story 3",
            "Andy se prepara para ir para a faculdade e, inesperadamente, seus leais brinquedos acabando sendo enviados para uma creche. As crianças e seus dedinhos pegajosos não têm cuidado ao brincar, de modo que os brinquedos decidem unir forças e planejar uma grande fuga. Algumas carinhas novas, umas de plástico e outras de pelúcia, juntam-se a essa incrível aventura: Ken, o namorado de Barbie, um ouriço-ator chamado Espeto e um ursinho de pelúcia rosa e com cheirinho de morango chamado Lotso.",
            "http://files.sistander.webnode.com.br/system_preview_detail_200000128-04629055c7/Toy-Story-3.jpg"),
        array(
            "Toy-story",
            "Toy Story 4",
            "Woody, Buzz Lightyear e o resto da turma embarcam em uma viagem com Bonnie e um novo brinquedo chamado Forky. A aventura logo se transforma em uma reunião inesperada quando o ligeiro desvio que Woody faz o leva ao seu amigo há muito perdido, Bo Peep.",
            "https://cinepop.com.br/wp-content/uploads/2018/04/Toy-Story-4-750x380.jpg"),
        array(
            "Friends",
            "Friends",
            "Seis jovens são unidos por laços familiares, românticos e, principalmente, de amizade, enquanto tentam vingar em Nova York. Rachel é a garota mimada que deixa o noivo no altar para viver com a amiga dos tempos de escola Monica, sistemática e apaixonada pela culinária. Monica é irmã de Ross, um paleontólogo que é abandonado pela esposa, que descobriu ser lésbica. Do outro lado do corredor do apartamento de Monica e Rachel, moram Joey, um ator frustrado, e Chandler, de profissão misteriosa. A turma é completa pela exótica Phoebe.",
            "https://2.bp.blogspot.com/-Ij2M6JzWHr0/V96q93tuGrI/AAAAAAAAheo/QSF43b9wYxYEUF5OW1pBj7eAKzg6ZHAYwCK4B/s1600/Friends-TV-show-on-NBC-canceled-no-season-11.jpg"),
        array(
            "Breaking-bed",
            "Breaking Bed",
            "Walter White (Bryan Cranston) é um professor de química na casa dos 50 anos que trabalha em uma escola secundária no Novo México. Para atender às necessidades de Skyler (Anna Gunn), sua esposa grávida, e Walt Junior (RJ Mitte), seu filho deficiente físico, ele tem que trabalhar duplamente. Sua vida fica ainda mais complicada quando descobre que está sofrendo de um câncer de pulmão incurável. Para aumentar rapidamente a quantidade de dinheiro que deixaria para sua família após sua morte, Walter usa seu conhecimento de química para fazer e vender metanfetamina, uma droga sintética. Ele conta com a ajuda do ex-aluno e pequeno traficante Jesse (Aaron Paul) e enfrenta vários desafios, incluindo o fato de seu concunhado ser um importante nome dentro da Agência Anti-Drogas da região.",
            "https://i0.wp.com/cloud.estacaonerd.com/wp-content/uploads/2019/05/15093546/breaking-bad-capa.jpg?fit=746%2C398&ssl=1"),
        array(
            "Got",
            "Game Of Thrones",
            "Há muito tempo, em um tempo esquecido, uma força destruiu o equilíbrio das estações. Em uma terra onde os verões podem durar vários anos e o inverno toda uma vida, as reivindicações e as forças sobrenaturais correm as portas do Reino dos Sete Reinos. A irmandade da Patrulha da Noite busca proteger o reino de cada criatura que pode vir de lá da Muralha, mas já não tem os recursos necessários para garantir a segurança de todos. Depois de um verão de dez anos, um inverno rigoroso promete chegar com um futuro mais sombrio. Enquanto isso, conspirações e rivalidades correm no jogo político pela disputa do Trono de Ferro, o símbolo do poder absoluto.",
            "https://simplesmentefeminino.com.br/wp-content/uploads/2018/04/game_of_thrones-e1524491140845.jpg"),
        array(
            "Stranger-things",
            "Stranger Things",
            "Em 6 de Novembro, 1983 na pequena cidade de Hawkins, Indiana, o garoto de 12 anos, Will Byers desaparece misteriosamente. A mãe de Will, Joyce, torna-se frenética e tenta encontrar Will enquanto o chefe de polícia Jim Hopper começa a investigar, e assim fazem também os amigos de Will: Dustin, Mike e Lucas. No dia seguinte, uma menina psicocinética que sabe o paradeiro de Will é encontrada pelos meninos. À medida que eles descobrem a verdade, uma sinistra agência do governo tenta encobri-los, enquanto uma força mais insidiosa espreita logo abaixo da superfície.",
            "https://entreterse.com.br/wp-content/uploads/2017/11/stranger.jpg"),
        array(
            "Greys-anatomy",
            "Greys Anatomy",
            "Os médicos do Grey Sloan Memorial Hospital lidam diariamente com casos e consequências de vida ou morte. É um no outro que eles encontram apoio, conforto, amizade e, às vezes, até mais que amizade... Juntos, eles descobrem o quanto a vida profissional e a pessoal podem ser complicadas e se misturarem no meio do caminho.",
            "https://entreterse.com.br/wp-content/uploads/2017/02/greys.jpg"),
        array(
            "Black-mirror",
            "Black Mirror",
            "Uma espécie de híbrido entre 'The Twilight Zone' e 'Tales of the Unexpected', Black Mirror explora sensações do mal-estar contemporâneo. Cada episódio conta uma história diferente, traçando uma antologia que mostra o lado negro da vida atrelada à tecnologia",
            "https://i.smalljoys.me/2018/01/black-mirror-logo-1.jpg?resize=1200,630"),
        array(
            "La-casa-de-papel",
            "La Casa de Papel",
            "Oito habilidosos ladrões se trancam na Casa da Moeda da Espanha com o ambicioso plano de realizar o maior roubo da história e levar com eles mais de 2 bilhões de euros. Para isso, a gangue precisa lidar com as dezenas de pessoas que manteve como refém, além dos agentes da força de elite da polícia, que farão de tudo para que a investida dos criminosos fracasse.",
            "https://almde50tons.files.wordpress.com/2018/03/casa-e1516976904459-820x380.png"),
    
    );

?>