<?php
    $matriz_elenco = array
    (
        array(
          "Maze-runner",
          "Dylan O'Brien",
          "Personagem: Thomas",
          "https://pmcvariety.files.wordpress.com/2016/03/maze-runner.jpg?w=1000&h=563&crop=1"),
        array(
          "Maze-runner",
          "Aml Ameen",
          "Personagem: Alby",
          "https://www.elefantevoador.com/wp-content/uploads/2015/11/The-Maze-runner-Alby-Aml-Ameen.jpg"),
        array(
          "Maze-runner",
          "Will Poulter",
          "Personagem: Gally",
          "http://si.wsj.net/public/resources/images/BN-EL964_poulte_G_20140910071817.jpg"),
        array(
          "Maze-runner",
          "Kaya Scodelario",
          "Personagem: Teresa",
          "https://besthqwallpapers.com/Uploads/21-12-2017/34414/thumb2-teresa-4k-maze-runner-the-death-cure-2018-movie-kaya-scodelario.jpg"),
        array(
          "Maze-runner",
          "Thomas Brodie-Sangster",
          "Personagem: Newt",
          "http://images6.fanpop.com/image/photos/40100000/Maze-runner-Newt-thomas-brodie-sangster-40121823-1200-600.jpg"),
        array(
          "Maze-runner",
          "Ki Hong Lee",
          "Personagem: Minho",
          "https://starschanges.com/wp-content/uploads/2015/11/Ki-Hong-Lee_1.jpg"),
        array(
          "Capita-marvel",
          "Brie Larson",
          "Personagem: Carol Danvers/Capitã Marvel",
          "https://i1.wp.com/www.nerdsite.com.br/wp-content/uploads/2019/04/brie-larson.jpg?fit=628%2C380&ssl=1"),
        array(
          "Capita-marvel",
          "Samuel L. Jackson",
          "Personagem: Nick Fury",
          "https://correio-cdn1.cworks.cloud/fileadmin/user_upload/06032019_capita_marvel_samuel.jpg"),
        array(
          "Capita-marvel",
          "Jude Law",
          "Personagem: Yon-Rogg/Starforce Commander",
          "http://br.web.img3.acsta.net/r_640_360/newsv7/18/09/06/23/09/5629194.jpg"),
        array(
          "Capita-marvel",
          "Clark Gregg",
          "Personagem: Phil Coulson",
          "https://i0.wp.com/www.jornadageek.com.br/wp-content/uploads/2018/03/Phill-Coulson.jpg?resize=696%2C398&ssl=1"),
        array(
          "Capita-marvel",
          "Ben Mendelsohn",
          "Personagem: Talos/Keller",
          "https://ovicio.com.br/wp-content/uploads/captain-marvel-skrull.png"),
        array(
          "Capita-marvel",
          "Gemma Shan",
          "Personagem: Minn-Erva",
          "https://cinepop.com.br/wp-content/uploads/2018/02/Gemma-Chan-capit%C3%A3-Marvel-750x380.jpg"),
        array(
          "Capita-marvel",
          "Lee Pace",
          "Personagem: Ronan",
          "http://br.web.img2.acsta.net/newsv7/18/04/03/20/02/2786447.jpg"),
        array(
          "Capita-marvel",
          "Annette Bening",
          "Personagem: Supreme Intelligence",
          "https://cinemacomrapadura.com.br/imagens/2018/05/20180509-bening-marvel.jpg"),
        array(
          "Como_treinar_seu_Dragao",
          "Jay Baruchel",
          "Personagem: Soluço",
          "https://cdn.mensagenscomamor.com/content/images/m000123579.jpg?v=0&w=340&h=200"),
        array(
          "Como_treinar_seu_Dragao",
          "Gerard Butler",
          "Personagem: Stoico",
          "https://assets.b9.com.br/wp-content/uploads/2014/06/butler.jpg"),
        array(
          "Como_treinar_seu_Dragao",
          "America Ferrera",
          "Personagem: Astrid",
          "http://recantoadormecido.com.br/wp-content/uploads/2014/01/How-to-Train-Your-Dragon-2-Official-Poster-Banner-PROMO-POSTER-XXLG-20JANEIRO2014-01-1-890x395.jpg"),  
        array(
          "Como_treinar_seu_Dragao",
          "Jonah Hill",
          "Personagem: Melequento",
          "https://comandonoticia.com.br/wp-content/uploads/2018/06/Screenshot_2018-06-07-13-12-28-1-1200x675.png"),
        array(
          "Como_treinar_seu_Dragao",
          "Christopher Mintzplasse",
          "Personagem: Perna de Peixe",
          "https://www.hypable.com/wp-content/uploads/2013/08/how-to-train-your-dragon-christopher-mintz-plasse.jpg"),
        array(
          "Como_treinar_seu_Dragao",
          "Craig Ferguson",
          "Personagem: Bocão",
          "https://www.glaad.org/sites/default/files/styles/760x400/public/images/2014-05/Craig-as-Gobber-in-How-to-Train-Your-Dragon-craig-ferguson-11601189-598-644.jpg?itok=Sj2aj9Ks"),
        array(
          "Como_treinar_seu_Dragao",
          "Kristen Wiig",
          "Personagem: Cabeça Quente",
          "https://vignette.wikia.nocookie.net/cartoonnetwork/images/7/74/Cabe%C3%A7a_Dura.png/revision/latest?cb=20140607025920&path-prefix=pt-br"),
        array(
          "Rei-leao",
          "Beyoncé",
          "Personagem: Nala",
          "https://ogimg.infoglobo.com.br/in/23796313-14a-ff5/FT1086A/652/beyonce-spirit-960x640.jpg"),
        array(
          "Rei-leao",
          "Donald Glover",
          "Personagem: Simba",
          "https://nit.pt/wp-content/uploads/2017/02/FotorCreated-754x394.jpg"),
        array(
          "Rei-leao",
          "Seth Rogen",
          "Personagem: Pumba",
          "https://ovicio.com.br/wp-content/uploads/the-lion-king-seth-rogen-pumbaa.jpg"),
        array(
          "Rei-leao",
          "James Earl Jones",
          "Personagem: Mufasa",
          "https://cinepop.com.br/wp-content/uploads/2017/02/oreileao_1-750x380.jpg"),
        array(
          "Rei-leao",
          "Billy Eichner",
          "Personagem: Timão",
          "http://www.magazine-hd.com/apps/wp/wp-content/uploads/2018/07/billy-eichner_timon.jpg"),
        array(
          "Chiwetel Ejiofor",
          "Personagem: Scar",
          "https://media.fstatic.com/JREyZlHmmgS3tLKYVVc6X4uUEWQ=/full-fit-in/629x300/media/articles/main/2017/08/03/chiwetel_ejiofor_and_lion_king_still_-_split_-_getty_-_h_2017-1_nlr6Qrq.jpg"),
        array(
          "Annabelle",
          "Annabelle Wallis",
          "Personagem: Mia",
          "https://m.media-amazon.com/images/M/MV5BZDkxMzc0ZTQtNWQyMy00MWM5LTljMTgtNGZkMmI5YjY5YzVhXkEyXkFqcGdeQXRzdGFzaWVr._V1_CR0,1,949,534_AL_UX477_CR0,0,477,268_AL_.jpg"),
        array(
          "Annabelle",
          "Ward Horton",
          "Personagem: John",
          "https://i.ytimg.com/vi/ZRAGgSPWqo8/maxresdefault.jpg"),
        array(
          "Annabelle",
          "Alfre Woodard",
          "Personagem: Evelyn",
          "http://br.web.img2.acsta.net/pictures/14/09/24/15/44/091473.jpg"),
        array(
          "Annabelle",
          "Eric Ladin",
          "Personagem: Detetive Clarkin",
          "https://s.hdnux.com/photos/32/37/26/6944170/3/gallery_medium.jpg"),
        array(
          "Annabelle",
          "Kerry O'Malley",
          "Personagem: Sharon Higgins",
          "https://m.media-amazon.com/images/M/MV5BNzU0YzQ4YmItNmU1ZS00MTk2LWExNDEtZmMzNzE0OTAyODRhXkEyXkFqcGdeQXVyNTQ3MjAzNTM@._V1_.jpg"),
        array(
          "Annabelle",
          "Tony Amendola",
          "Personagem: Padre Perez",
          "https://m.media-amazon.com/images/M/MV5BMTQ1ODY1ODM1MV5BMl5BanBnXkFtZTgwODgxNjY3MjE@._V1_SX1777_CR0,0,1777,744_AL_.jpg"),
        array(
          "Annabelle",
          "Gabriel Bateman",
          "Personagem: Robert",
          "https://m.media-amazon.com/images/M/MV5BMzg5ZThjZTQtZWQxZC00NTQzLWI3NmMtNWRjMjViNTJhZGEyXkEyXkFqcGdeQXVyNTQ3MjAzNTM@._V1_SX1777_CR0,0,1777,999_AL_.jpg"),
        array(
          "Toy-story",
          "Tom Hanks",
          "Personagem: Xerife Woody",
          "https://www.unilad.co.uk/wp-content/uploads/2019/01/toystory1.jpg"),
        array(
          "Toy-story",
          "Tim Allen",
          "Personagem: Buzz Lightyear",
          "https://s.yimg.com/uu/api/res/1.2/USXKTIiWn7oI3HICeQI8Hw--~B/aD0xODAwO3c9MjcwMDtzbT0xO2FwcGlkPXl0YWNoeW9u/http://media.zenfs.com/en-US/homerun/people_218/c9af279624d16c44f0321ec07dffd3ad"),
        array(
          "Toy-story",
          "Don Rickles",
          "Personagem: Sr. Cabeça de Batata",
          "https://www.etonline.com/sites/default/files/styles/max_970x546/public/images/2019-03/1280_don_rickles_0.jpg?itok=xW6oRAyb&h=3600408e"),
        array(
          "Toy-story",
          "Annie Potts",
          "Personagem: Betty",
          "https://media1.popsugar-assets.com/files/thumbor/-uel_OEaU192jA7fF0w_CQZ5t14/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2018/11/13/711/n/1922283/eb247d93853f5a9b_toy7/i/Annie-Potts-Bo-Peep.jpg"),
        array(
          "Toy-story",
          "Wallace Shawn",
          "Personagem: Rex",
          "http://images.dailyhive.com/20170321163606/Wallace-Shawn-calgary-expo-twitter.png"),
        array(
          "Toy-story",
          "John Ratzenberger",
          "Personagem: Porquinho",
          "https://i.pinimg.com/originals/f8/3d/f6/f83df6bfea6d7584ce3e58f1f8eb7192.jpg"),
        array(
          "Toy-story",
          "John Morris",
          "Personagem: Andy",
          "https://i.pinimg.com/originals/14/97/c3/1497c3166c6e6765b1ba6b939d2308fd.jpg"),
        array(
          "Friends",
          "Jennifer Aniston",
          "Personagem: Rachel Green",
          "https://observatoriodocinema.bol.uol.com.br/wp-content/uploads/2019/09/Jennifer-Aniston.jpg"),
        array(
          "Friends",
          "Courteney Cox",
          "Personagem: Monica Geller",
          "https://abrilveja.files.wordpress.com/2016/05/alx_entretenimento-courteney-cox-20150420-002_original.jpeg"),
        array(
          "Friends",
          "Matthew Perry",
          "Personagem: Chandler Bing",
          "https://observatoriodosfamosos.bol.uol.com.br/portal/wp-content/uploads/2019/08/Matthew-Perry.jpg"),
        array(
          "Friends",
          "Lisa Kudrow",
          "Personagem: Phoebe Buffay",
          "https://media.wfaa.com/assets/CCT/images/783089fd-c985-4aaa-9dc5-403652c112a0/783089fd-c985-4aaa-9dc5-403652c112a0_750x422.jpg"),
        array(
          "Friends",
          "Matt LeBlanc",
          "Personagem: Joey Tribban",
          "https://media3.s-nbcnews.com/i/newscms/2018_11/1324118/matt-leblanc-today-180312-tease_c8dfe4dbeb4fc37d83be67a19049c758.jpg"),
        array(
          "Friends",
          "Davi Schwimmer",
          "Personagem: Ross Geller",
          "https://nyppagesix.files.wordpress.com/2019/09/david-schwimmer.jpg?quality=90&strip=all&w=618&h=410&crop=1"),
        array(
          "Breaking-bed",
          "Bryan Cranston",
          "Personagem: Walter White",
          "https://quartaparedepop.com.br/wp-content/uploads/2018/11/eaking-bad-walter-white-752x438.jpg"),
        array(
          "Breaking-bed",
          "Aaron Paul",
          "Personagem: Jesse Pinkman",
          "http://br.web.img2.acsta.net/r_640_360/newsv7/19/02/13/19/45/1105147.jpg"),
        array(
          "Breaking-bed",
          "Anna Gunn",
          "Personagem: Skyler White",
          "https://i0.wp.com/www.usmagazine.com/wp-content/uploads/2019/07/Anna-Gunn-Extreme-Sexism-Experience-Breaking-Bad-02.jpg?crop=127px%2C53px%2C1968px%2C1111px&resize=1200%2C675&ssl=1"),
        array(
          "Breaking-bed",
          "RJ Mitte",
          "Personagem: Walter White Jr",
          "http://prod-upp-image-read.ft.com/835fde60-7454-11e6-bf48-b372cdb1043a"),
        array(
          "Breaking-bed",
          "Dean Norris",
          "Personagem: Hank Schrader",
          "https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1439,w_2560,x_0,y_0/dpr_1.5/c_limit,w_1044/fl_lossy,q_auto/v1492198506/articles/2014/06/06/from-breaking-bad-to-benjamin-franklin-dean-norris-on-life-after-hank-schrader/140604-stern-norris-tease_vpriqt"),
        array(
          "Breaking-bed",
          "Betsy Brandt",
          "Personagem: Marie Schrader",
          "https://images.amcnetworks.com/blogs.amctv.com/wp-content/uploads/2013/08/bb-s5b-betsy-brandt-interview-560.jpg"),
        array(
          "Got",
          "Emilia Clarke",
          "Personagem: Daenerys Targaryen",
          "https://observatoriodocinema.bol.uol.com.br/wp-content/uploads/2019/02/Emilia-Clarke-Game-of-Thrones.jpg"),
        array(
          "Got",
          "Kit Harington",
          "Personagem: Jon Snow",
          "https://i0.wp.com/cloud.estacaonerd.com/wp-content/uploads/2019/04/14172146/JON-SNOW.jpeg?fit=2500"),
        array(
          "Got",
          "Sophie Turner",
          "Personagem: Sansa Stark",
          "https://conteudo.imguol.com.br/75/2019/04/12/sophie-turner-de-game-of-thrones-1555081958417_615x300.png"),
        array(
          "Got",
          "Maisie Williams",
          "Personagem: Arya Stark",
          "https://akns-images.eonline.com/eol_images/Entire_Site/2019421/rs_1024x759-190521061351-1024-Arya-Stark-Maisie-Williams-GOT-LT-052129-HBO.jpg?fit=inside|900:auto&output-quality=90"),
        array(
          "Got",
          "Lena Headey",
          "Personagem: Cersei Lannister",
          "https://assets.papelpop.com/wp-content/uploads/2019/05/6-helen-sloan-hbo-2.jpg"),
        array(
          "Got",
          "Nikolaj Coster Waldau",
          "Personagem: Jamine Lannister",
          "https://observatoriodeseries.bol.uol.com.br/wp-content/uploads/2019/04/917f6935adbb4896a17d9ffe35dad402.jpg"),
          array(
            "Stranger-things",
            "Millie Bobby Brown",
            "Personagem: Onze",
            "https://observatoriodocinema.bol.uol.com.br/wp-content/uploads/2019/08/cropped-millie-bobby-brown-2.jpeg"),
          array(
            "Stranger-things",
            "Finn Wolfhard",
            "Personagem: Mike",
            "https://ogimg.infoglobo.com.br/in/22026747-c10-e54/FT1086A/652/xFinn-Wolfhard-attends-Netflix27s-Stranger-Things-2-premiere-on-October-26-2017-in-West.jpg.pagespeed.ic.kpnuI6spsK.jpg"),
          array(
            "Stranger-things",
            "Gaten Matarazzo",
            "Personagem: Dustin",
            "https://abrilcapricho.files.wordpress.com/2017/10/gaten-matarazzo-stranger-things-cirurgia-dentes-reais1.jpg?quality=85&strip=info&w=874"),
          array(
            "Stranger-things",
            "Noah Schanapp",
            "Personagem: Will",
            "https://worldofwonder.net/wp-content/uploads/2019/07/Screen-Shot-2019-07-10-at-10.17.58-AM-1000x660.png"),
          array(
            "Stranger-things",
            "Natalia Dyer",
            "Personagem: Nancy",
            "https://abrilcapricho.files.wordpress.com/2017/10/stranger-things-natalia-dyer-nancy-jonathan-byers-charlie.jpeg?quality=85&strip=info&w=1024"),
          array(
            "Stranger-things",
            "Caleb McLaughlin",
            "Personagem: Lukas",
            "https://peopledotcom.files.wordpress.com/2019/07/caleb-mclaughlin.jpg?w=2700&h=1800"),
          array(
            "Stranger-things",
            "Joey Keery",
            "Personagem: Steve Harrington",
            "https://culturamaniac.files.wordpress.com/2017/11/who-joe-keery.jpg"),
          array(
            "Stranger-things",
            "David Harbour",
            "Personagem: Hopper",
            "https://media.hugogloss.uol.com.br/uploads/2019/07/jim-hopper-stranger-things.jpg"),
          array(
            "Stranger-things",
            "Charlie Heaton",
            "Personagem: Jonathan",
            "https://ksassets.timeincuk.net/wp/uploads/sites/55/2017/10/Charlie-Heaton-Stranger-Things-GettyImages-634298026-920x584.jpg"),
          array(
            "Greys-anatomy",
            "Ellen Pompeo",
            "Personagem: Meredith Grey",
            "https://nit.pt/wp-content/uploads/2018/09/989e5dbd43cbeeb52f353a1255814192-754x394.jpg"),
          array(
            "Greys-anatomy",
            "Justin Chambers",
            "Personagem: Alex Karev",
            "https://mixdeseries.com.br/wp-content/uploads/2018/07/Alex-Karev-Grey-Anatomy-GIFs.jpg"),
          array(
            "Greys-anatomy",
            "Chandra Wilson",
            "Personagem: Miranda Bailey",
            "https://f.i.uol.com.br/fotografia/2019/07/05/15623730335d1feba9d7dd3_1562373033_5x2_lg.jpg"),
          array(
            "Greys-anatomy",
            "Patrick Dempsey",
            "Personagem: Derek Shepherd",
            "https://i0.wp.com/www.zapping-tv.com/wp-content/uploads/2015/04/Patrick-Dempsey.jpg"),
          array(
            "Greys-anatomy",
            "James Pickens Jr",
            "Personagem: Richard Webber",
            "http://br.web.img2.acsta.net/pictures/17/09/19/11/06/1342163.jpg"),
          array(
            "Greys-anatomy",
            "Sandra Oh",
            "Personagem: Cristina Yang",
            "http://br.web.img2.acsta.net/r_640_360/newsv7/18/03/23/18/40/2817360.jpg"),
          array(
            "Black-mirror",
            "Bryce Dallas Howard",
            "Personagem: Lacie",
            "https://i0.wp.com/pipocamoderna.com.br/wp-content/uploads/2016/08/black-mirror-season-3-bryce-dallas-howard.jpg"),
          array(
            "Black-mirror",
            "Cristin Milioti",
            "Personagem: Nanette Cole",
            "https://ewedit.files.wordpress.com/2018/05/blackmirror_s4_callister_00552_v1.jpg?crop=472px%2C108px%2C1978px%2C1039px&resize=1200%2C630"),
          array(
            "Black-mirror",
            "Hayley Atwell",
            "Personagem: Martha",
            "https://i.pinimg.com/originals/5a/9d/a8/5a9da874d6596300dd6a1781c8a160fb.jpg"),
          array(
            "Black-mirror",
            "Hannah John-Kamen",
            "Personagem: Selma Telse",
            "https://hips.hearstapps.com/digitalspyuk.cdnds.net/16/42/1477045456-black-mirror-hannah.jpg?resize=480:*"),
          array(
            "Black-mirror",
            "Jon Hamm",
            "Personagem: Matt",
            "https://exitoina.uol.com.br/media/_versions/legacy/2019/06/02/jon-hamm-1151420_widelg.jpg"),
          array(
            "Black-mirror",
            "Daniel Kaluuya",
            "Personagem: Bing",
            "https://m.media-amazon.com/images/M/MV5BNjI0Y2I2MzAtNjVhNS00MGFhLTg5ZDMtNjRlMmIxNTA3MjdlXkEyXkFqcGdeQXVyODExNTExMTM@._V1_.jpg"),
          array(
            "La-casa-de-papel",
            "Úrsula Corberó",
            "Personagem: Tokio",
            "https://blog.morumbishopping.com.br/wp-content/uploads/2018/04/Tokio-destaque.jpg"),
          array(
            "La-casa-de-papel",
            "Álvaro Morte",
            "Personagem: Professor",
            "https://imagem.natelinha.uol.com.br/grande/oprofessorlacasadepapel_eafba3a476292cf66d8c0cf136e59ed94a7166e6.jpeg"),
          array(
            "La-casa-de-papel",
            "Itziar Ituño",
            "Personagem: Inspetora Raquel Murillo",
            "https://media.metrolatam.com/2019/08/05/descarga-91381c812002f54190a4d5d54029e20b-1200x600.jpg"),
          array(
            "La-casa-de-papel",
            "Miguel Herrán",
            "Personagem: Rio",
            "https://i0.wp.com/pipocasclub.com.br/wp-content/uploads/2019/09/la-casa-de-papel-miguel_859914-11932120.jpg?resize=1280%2C640&ssl=1"),
          array(
            "La-casa-de-papel",
            "Alba Flores",
            "Personagem: Nairobi",
            "https://media.metrolatam.com/2018/04/23/0028994013-91091d61d55ccd73978f33ef41c41f74-1200x600.jpg"),
          array(
            "La-casa-de-papel",
            "Pedro Afonso",
            "Personagem: Berlim",
            "https://www.n-tv.pt/files/2018/04/berlim_4AxG6ax.jpg"),
          array(
            "La-casa-de-papel",
            "Jaime Lorente",
            "Personagem: Denver",
            "https://www.paraeles.pt/wp-content/uploads/2019/01/jaime_lorente.png"),
    );

?>